# Consola: útil al principio; para medir consumo real conviene desactivarla.
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# I2C y GPIO usados por el sensor y su alimentación conmutada.
CONFIG_GPIO=y
CONFIG_I2C=y

# Gestión de energía del sistema y de dispositivos.
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Driver genérico que convierte PC7 en un dominio de alimentación.
CONFIG_POWER_DOMAIN=y

# BLE integrado del STM32WB55.
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="Soil sensor"
