# Console / UART
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y

# Debug / logging
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_EVENTS=y

# GPIO
CONFIG_GPIO=y

# Nota:
# Si Smart App Control / Device Guard bloquea readelf al generar zephyr.stat,
# puedes probar temporalmente:
# CONFIG_OUTPUT_STAT=n
